AG query; telegram channel scripts; clean up
xrnl/rebel_management_utilities pull request #12
Opened 2021-01-10 17:07 UTC by martijnmartijnmartijnmartijn

I added:
- An action network query to request all AG data. 
- A generalised function to add people to a telegram channel.
- Some function to convert Dutch geo data. 

I also cleaned up the codebase somewhat:
- Removed queries for the deprecated local_group field.
- Removed synchronisation of AG data to a google sheets file.

2021-01-16 15:39 UTC, moritzcopter requested changes
Thanks for the Pull request @martijnmartijnmartijnmartijn !
There are a few bugs in the code which we should fix before merging.

Do you use an IDE for coding? These can highlight and help you find bugs like this very easily.  I can recommend PyCharm which I am using at work almost every day.

2021-01-16 15:39 UTC, moritzcopter commented on rebel_management_utilities/members.py
> -    return local_group
I dont think we want to delete this block - otherwise we wont be able to find the local group of people who signed up before we introduced `municipalities`

2021-01-16 15:39 UTC, moritzcopter commented on rebel_management_utilities/action_network.py
> -    return 'Other'
Any reason to delete this? This breaks the function below (line 93) - also this logic is still valid I think

2021-01-16 15:39 UTC, moritzcopter commented on telegram_channels/sync_telegram_channels.py
> +                logs["other_error"].append(p)
Wouldnt it be easier to just log this (e.g. with `logging.warning`) or so?

2021-01-16 15:39 UTC, moritzcopter commented on telegram_channels/sync_telegram_channels.py
> +        first_name=user["given_name"],
`user` is not defined here no? - I think you mean `person`

2021-01-16 15:39 UTC, moritzcopter commented on rebel_management_utilities/convert_geodata.py
> +        print(f'Coordinates not found: {postcode}')
`postcode` is not defined here no?

2021-01-16 15:39 UTC, moritzcopter commented on telegram_channels/sync_telegram_channels.py
> +    p_in_channel = [p.phone for user in await client.get_participants(channel) if p.phone]
`client` is not defined here

2021-01-16 15:39 UTC, moritzcopter commented on telegram_channels/sync_telegram_channels.py
> +            except Error as e: # Other errors.
I think you want to use `Exception` here

2021-01-18 13:42 UTC, martijnmartijnmartijnmartijn commented on rebel_management_utilities/members.py
> -    return local_group
We actually converted everyones location data to a municipality to allow this, included the local_groups. I think Collin actually just finished this last week and deleted the local_group field altogether. I just queried everyone and no one has the field anymore, so we should be okay deleting this.

2021-01-18 16:38 UTC, martijnmartijnmartijnmartijn commented on rebel_management_utilities/convert_geodata.py
> +        print(f'Coordinates not found: {postcode}')
Fixed this!

2021-01-18 16:40 UTC, martijnmartijnmartijnmartijn commented on rebel_management_utilities/action_network.py
> -    return 'Other'
you're right, not sure what I was thinking - I added it in again.

2021-01-18 16:40 UTC, martijnmartijnmartijnmartijn commented on telegram_channels/sync_telegram_channels.py
> +    p_in_channel = [p.phone for user in await client.get_participants(channel) if p.phone]
Fixed

2021-01-18 16:40 UTC, martijnmartijnmartijnmartijn commented on telegram_channels/sync_telegram_channels.py
> +            except Error as e: # Other errors.
Fixed

2021-01-18 16:41 UTC, martijnmartijnmartijnmartijn commented on telegram_channels/sync_telegram_channels.py
> +                logs["other_error"].append(p)
Yeah that's better. I added this

2021-01-18 16:41 UTC, martijnmartijnmartijnmartijn commented on telegram_channels/sync_telegram_channels.py
> +        first_name=user["given_name"],
Fixed

2021-01-18 16:44 UTC, martijnmartijnmartijnmartijn commented
@moritzcopter Thanks for the thorough review. I've now installed an IDE, and immediately the naming errors you mention ed popped up. I've always used a simple text editor so this is pretty damn nice haha. I think I fixed everything you requested now. 

In the mean time I added two more things:
- A function in members.py which can be used to update a persons data in Action Network.
- A function in action_network.py which computes an overview of the number of people in each local group, as well as in each municipality. I'm using it to create a map for outreach & training (check it out: https://www.datawrapper.de/_/coqXh/)

2021-01-20 21:28 UTC, moritzcopter commented on rebel_management_utilities/members.py
> -    return local_group
👍

2021-01-20 21:30 UTC, moritzcopter approved these changes

2021-01-20 21:32 UTC, merged

2021-01-20 21:34 UTC, moritzcopter commented
Thanks for the changes Martijn, that map looks pretty cool 👌  - I merged your changes